### ISSUE TITLE
dtanks executable …

### ISSUE THREAD

**Issue by russel** [masterthought/dtanks#1]
…probably shouldn't be in the repo.

**Comment by russel** [comment]
Also dub.selections.json should not be part of the repository.

I am also thinking maybe the prebuild DSFL libraries should be got some other way than having all architectures prebuilt ones in the repository.

**Comment by kingsleyh** [comment]
I will remove tanks and dub.selections.json and put them in .gitignore

I didn’t want people to have too much trouble getting things working on their OS so thats why I included the DFML libs for different platforms.
However - I haven’t been able to get DSFML to build on windows yet - not sure if it’s a problem with the prebuilt win32 dsfml stuff - haven’t tried yet on linux but will do that shortly. OS X is fine since thats the platform I use.

—K

**Comment by russel** [comment]
I suspect the prebuilt libraries will only work for those people with exactly the same set up as the one used for the build :-(

**Comment by kingsleyh** [comment]
removed these now
